version: 1.0.{build}
image: Visual Studio 2017
before_build:
 - appveyor-retry dotnet restore -v Minimal
build:
  verbosity: minimal
on_success:
- nuget install Hub-Nuget -Version 1.1.0
- Hub-NuGet.1.1.0\tools\buildBom.exe --hub_deploy_bdio=false --hub_create_merged_bdio=true
- cd blackduck
- dir
- cd ..
- bash test-bash.sh ./blackduck/*.jsonld
